adding app.set and getting settings
masotime/mock-express pull request #10
Opened 2017-06-12 20:22 UTC by scottnath

Need to add/retrieve settings like in `[app.set](https://expressjs.com/en/api.html#app.set)`.

thank you!
Scott

2017-06-14 19:08 UTC, scottnath commented
@masotime also added `req.body` and `res.status` with tests.

thanks!

2017-06-16 05:07 UTC, masotime requested changes
Thanks for adding the features @scottnath, I really appreciate you taking the time to do it. The module's a little outdated (still in Node 0.x era when we're all working in ES2015+ these days).

I'm good with merging, but I'd request you remove the `body` feature - such specific functionality shouldn't be necessary and your test / use-case can still pass (ref: comments)

Thanks!

2017-06-16 05:07 UTC, masotime commented on lib/mockexpress.js
> +      if (requestObject.get('body')) {
This special case should not be necessary. The module doesn't enforce any rules on req (apart from `.query`, `.method`, `.url` as defined in the `invoke` function above. You can simply set `req.body` before calling `invoke`, ref - test below.

2017-06-16 05:07 UTC, masotime commented on test/test.js
> +		const req = app.makeRequest({ 'body': { foo: 'bar' } });
So you don't need to set `body` here.

2017-06-16 05:07 UTC, masotime commented on test/test.js
> +		app.invoke('put', '/test/body', req);
Before this statement, just have
```
req.body = { foo: 'bar' }
```

2017-07-08 10:12 UTC, masotime commented
LGTM 👍

2017-07-08 10:14 UTC, merged

2017-07-10 13:40 UTC, scottnath commented
Thanks @masotime!